encuesta/apps/opciones/urls.py
from django.urls import path
from .views import listarpreguntas, respuestas, reporte

urlpatterns = [
    path ('listar/<int:id>', listarpreguntas, name= 'listarpreguntas'),
    path('respuestas', respuestas, name='respuestas'),
    path('pdf/', reporte.as_view(), name='pdf'), 
]

encuesta/encuesta/urls.py
from django.contrib import admin
from django.urls import include, path
from apps.personas.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('personas/', include(('apps.personas.urls', 'personas'))),
    path('opciones/', include(('apps.opciones.urls', 'opciones'))),
    path('', home, name='index')
]

encuesta/apps/opciones/models.py
from django.db import models
from apps.personas.models import Datos

# Create your models here.
class encuesta(models.Model):
    nombre_encuesta = models.CharField(max_length=100, blank=False, null=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre_encuesta

    class Meta:
        verbose_name = 'Encuesta'
        verbose_name_plural = 'Encuestas'
        ordering = ['id']

class pregunta1(models.Model):
    encuesta1 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 1'
        verbose_name_plural = 'Pregunta 1'
        ordering = ['id']



class opciones1(models.Model):
    opciones = (
        ('Poco Saludable', 'Poco Saludable'),
        ('Regular Saludable', 'Regular Saludable'),
        ('Saludable', 'Saludable'),
        ('Muy Saludable', 'Muy Saludable'),
        ('Excelente Saludable', 'Excelente Saludable')
    )
    encuesta = models.IntegerField(blank=False, null=False)
    opcion = models.CharField(max_length=100, choices=opciones)
    
    def __str__(self):
        return self.opcion
    
    class Meta:
        verbose_name = 'Respuesta 1'
        verbose_name_plural = 'Respuesta 1'
        ordering = ['id']

class pregunta2(models.Model):
    encuesta2 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 2'
        verbose_name_plural = 'Pregunta 2'
        ordering = ['id']

class opciones2(models.Model):
    opciones = (
        ('SI', 'SI'),
        ('NO', 'NO')
    )
    encuesta2 = models.IntegerField(blank=False, null=False)
    opcion2 = models.CharField(max_length=100, choices=opciones)

    def __str__(self):
        return self.opcion2
    
    class Meta:
        verbose_name = 'Respuesta 2'
        verbose_name_plural = 'Respuesta 2'
        ordering = ['id']

class pregunta3(models.Model):
    encuesta3 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 3'
        verbose_name_plural = 'Pregunta 3'
        ordering = ['id']

class opciones3(models.Model):
    opciones = (
        ('Presión alterial Alta', 'Presion alterial Alta'),
        ('Diabetes', 'Diabetes'),
        ('Hemolifia', 'Hemofilia'),
        ('Otro', 'Otro'),
        ('Ninguna', 'Ninguna')
    )
    encuesta3 = models.IntegerField(blank=False, null=False)
    opcion3 = models.CharField(max_length=100, choices=opciones)

    def __str__(self):
        return self.opcion3

    
    class Meta:
        verbose_name = 'Respuesta 3'
        verbose_name_plural = 'Respuesta 3'
        ordering = ['id']

class pregunta4(models.Model):
    encuesta4 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 4'
        verbose_name_plural = 'Pregunta 4'
        ordering = ['id']

class opciones4(models.Model):
    opciones = (
        ('Si, a ambos', 'Si, a ambos'),
        ('Solo a las Drogas', 'Solo a las Drogas'),
        ('Solo al alcohol', 'Solo al alcohol'),
        ('Ninguna', 'Ninguna')
    )
    encuesta4 = models.IntegerField(blank=False, null=False)
    opcion4 = models.CharField(max_length=100, choices=opciones)

    def __str__(self):
        return self.opcion4

    class Meta:
        verbose_name = 'Respuesta 4'
        verbose_name_plural = 'Respuesta 4'
        ordering = ['id']

class pregunta5(models.Model):
    encuesta5 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 5'
        verbose_name_plural = 'Pregunta 5'
        ordering = ['id']

class opciones5(models.Model):
    opciones = (
        ('Una vez cada 3 meses', 'Una vez cada 3 meses'),
        ('Una vez cada 6 meses', 'Una vez cada 6 meses'),
        ('Una vez cada al año', 'Una vez al año'),
        ('Solo cuando es necesario', 'Solo cuando es necesario'),
        ('Nunca lo hago', 'Nunca lo hago')
    )
    encuesta5 = models.IntegerField(blank=False, null=False)
    opcion5 = models.CharField(max_length=100, choices=opciones)
    

    def __str__(self):
        return self.opcion5

    class Meta:
        verbose_name = 'Respuesta 5'
        verbose_name_plural = 'Respuesta 5'
        ordering = ['id']

class pregunta6(models.Model):
    encuesta6 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 6'
        verbose_name_plural = 'Pregunta 6'
        ordering = ['id']

class opciones6(models.Model):
    opciones = (
        ('Excelente', 'Excelente'),
        ('Muy Bien', 'Muy Bien'),
        ('Promedio', 'Promedio'),
        ('Mal', 'Mal'),
        ('Muy mal', 'Muy mal')
    )
    encuesta6 = models.IntegerField(blank=False, null=False)
    opcion6 = models.CharField(max_length=100, choices=opciones)
    
    def __str__(self):
        return self.opcio6

    class Meta:
        verbose_name = 'Respuesta 6'
        verbose_name_plural = 'Respuesta 6'
        ordering = ['id']

class pregunta7(models.Model):
    encuesta7 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 7'
        verbose_name_plural = 'Pregunta 7'
        ordering = ['id']

class opciones7(models.Model):
    opciones = (
        ('Excelente Capacidad', 'Excelente Capacidad'),
        ('Buena Capacidad', 'Buena Capacidad'),
        ('Capacidad Moderada', 'Capacidad Moderada'),
        ('Deterioro Grave Capacidad', 'Deterioro Grave Capacidad'),
        ('Deterioro total de la Capacidad', 'Deterioro total de la Capacidad')
    )
    encuesta7 = models.IntegerField(blank=False, null=False)
    opcion7 = models.CharField(max_length=100, choices=opciones)
    
    def __str__(self):
        return self.opcion7
    
    class Meta:
        verbose_name = 'Respuesta 7'
        verbose_name_plural = 'Respuesta 7'
        ordering = ['id']

class pregunta8(models.Model):
    encuesta8 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 8'
        verbose_name_plural = 'Pregunta 8'
        ordering = ['id']

class opciones8(models.Model):
    opciones = (
        ('Sin ayuda', 'Sin ayuda'),
        ('Con algo de ayuda', 'Con algo de ayuda'),
        ('Completamente con ayuda', 'Completamente con ayuda')
    )
    encuesta8 = models.IntegerField(blank=False, null=False)
    opcion8 = models.CharField(max_length=100, choices=opciones)

    def __str__(self):
        return self.opcion8

    class Meta:
        verbose_name = 'Respuesta 8'
        verbose_name_plural = 'Respuesta 8'
        ordering = ['id']

class pregunta9(models.Model):
    encuesta9 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 9'
        verbose_name_plural = 'Pregunta 9'
        ordering = ['id']

class opciones9(models.Model):
    opciones = (
        ('Completamente desacuerdo', 'Completamente desacuerdo'),
        ('Algo en desacuerdo', 'Algo en desacuerdo'),
        ('Neutral', 'Neutral'),
        ('Un poco acuerdo', 'Un poco acuerdo'),
        ('Completamente acuerdo', 'Completamente acuerdo')
    )
    encuesta9 = models.IntegerField(blank=False, null=False)
    opcion9 = models.CharField(max_length=100, choices=opciones)

    def __str__(self):
        return self.opcion9

    class Meta:
        verbose_name = 'Respuesta 9'
        verbose_name_plural = 'Respuesta 9'
        ordering = ['id']

class pregunta10(models.Model):
    encuesta10 = models.ForeignKey(encuesta, on_delete=models.CASCADE)
    texto = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.texto
    
    class Meta:
        verbose_name = 'Pregunta 10'
        verbose_name_plural = 'Pregunta 10'
        ordering = ['id']

class opciones10(models.Model):
    opciones = (
        ('SI', 'SI'),
        ('NO', 'NO'),
    )
    encuesta10 = models.IntegerField(blank=False, null=False)
    opcion10 = models.CharField(max_length=100, choices=opciones)
    
    def __str__(self):
        return self.opcion10
    
    class Meta:
        verbose_name = 'Respuesta 10'
        verbose_name_plural = 'Respuesta 10'
        ordering = ['id']

encuesta/apps/opciones/forms.py
from django import forms
from .models import opciones1, opciones2, opciones3, opciones4, opciones5, opciones6, opciones7, opciones8, opciones9, opciones10

class Op1Form(forms.ModelForm):
    class Meta:
        model = opciones1
        fields = ['encuesta','opcion']

class Op2Form(forms.ModelForm):
    class Meta:
        model = opciones2
        fields = ['encuesta2','opcion2']

class Op3Form(forms.ModelForm):
    class Meta:
        model = opciones3
        fields = ['encuesta3','opcion3']

class Op4Form(forms.ModelForm):
    class Meta:
        model = opciones4
        fields = ['encuesta4','opcion4']

class Op5Form(forms.ModelForm):
    class Meta:
        model = opciones5
        fields = ['encuesta5','opcion5']

class Op6Form(forms.ModelForm):
    class Meta:
        model = opciones6
        fields = ['encuesta6','opcion6']

class Op7Form(forms.ModelForm):
    class Meta:
        model = opciones7
        fields = ['encuesta7','opcion7']

class Op8Form(forms.ModelForm):
    class Meta:
        model = opciones8
        fields = ['encuesta8','opcion8']

class Op9Form(forms.ModelForm):
    class Meta:
        model = opciones9
        fields = ['encuesta9','opcion9']

class Op10Form(forms.ModelForm):
    class Meta:
        model = opciones10
        fields = ['encuesta10','opcion10']

encuesta/apps/opciones/views.py
import io
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import View
from .models import encuesta, pregunta1, opciones1, opciones2, opciones3, opciones4, opciones5, opciones6, opciones7, opciones8, opciones9, opciones10, pregunta2, pregunta3, pregunta4, pregunta5, pregunta6, pregunta7, pregunta8, pregunta9, pregunta10
from apps.personas.models import Datos
from .forms import Op1Form, Op2Form, Op3Form, Op4Form, Op5Form, Op6Form, Op7Form, Op8Form, Op9Form, Op10Form
from django.http import FileResponse
from django.template.loader import get_template

#Reportlab libreria
import reportlab
from django.conf import settings
from io import BytesIO
from reportlab.pdfgen import canvas
from django.views.generic import View
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.charts.piecharts import Pie
from reportlab.pdfbase.pdfmetrics import stringWidth, EmbeddedType1Face, registerTypeFace, Font, registerFont
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin, Rect
from reportlab.lib.colors import PCMYKColor
from reportlab.graphics import renderPDF
from reportlab.lib.pagesizes import A4
from reportlab.graphics.charts.lineplots import LinePlot
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.widgets.markers import makeMarker




def listarpreguntas(request, id):
    pre1 = pregunta1.objects.all()
    pre2 = pregunta2.objects.all()
    pre3 = pregunta3.objects.all()
    pre4 = pregunta4.objects.all()
    pre5 = pregunta5.objects.all()
    pre6 = pregunta6.objects.all()
    pre7 = pregunta7.objects.all()
    pre8 = pregunta8.objects.all()
    pre9 = pregunta9.objects.all()
    pre10 = pregunta10.objects.all()
    usuario = Datos.objects.get(id = id)
    if request.method == 'POST':
        op1_form = Op1Form(request.POST)
        op2_form = Op2Form(request.POST)
        op3_form = Op3Form(request.POST)
        op4_form = Op4Form(request.POST)
        op5_form = Op5Form(request.POST)
        op6_form = Op6Form(request.POST)
        op7_form = Op7Form(request.POST)
        op8_form = Op8Form(request.POST)
        op9_form = Op9Form(request.POST)
        op10_form = Op10Form(request.POST)
        if op1_form.is_valid():
            op1_form.save()
            op2_form.save()
            op3_form.save()
            op4_form.save()
            op5_form.save()
            op6_form.save()
            op7_form.save()
            op8_form.save()
            op9_form.save()
            op10_form.save()
            return redirect('personas:listarpersona')
    else:
        op1_form = Op1Form()
        op2_form = Op2Form()
        op3_form = Op3Form()
        op4_form = Op4Form()
        op5_form = Op5Form()
        op6_form = Op6Form()
        op7_form = Op7Form()
        op8_form = Op8Form()
        op9_form = Op9Form()
        op10_form = Op10Form()


    return render (request, 'opciones/listar.html', {'pre1': pre1, 'op1_form': op1_form, 'pre2': pre2, 'op2_form': op2_form, 'pre3': pre3, 'op3_form': op3_form, 'pre4': pre4,  'op4_form': op4_form,'pre5': pre5, 'op5_form': op5_form, 'pre6': pre6, 'op6_form': op6_form,  'pre7': pre7,  'op7_form': op7_form, 'pre8': pre8, 'op8_form': op8_form, 'pre9': pre9, 'op9_form': op9_form, 'pre10': pre10,  'op10_form': op10_form, 'usuario': usuario.id})

def respuestas(request):
    pre1 = list(pregunta1.objects.all())
    res1 = list(opciones1.objects.values('opcion'))
    res1_op1 = res1.count({'opcion': 'Poco Saludable'})
    res1_op2 = res1.count({'opcion': 'Regular Saludable'})
    res1_op3 = res1.count({'opcion': 'Saludable'})
    res1_op4 = res1.count({'opcion': 'Muy Saludable'})
    res1_op5 = res1.count({'opcion': 'Excelente Saludable'})    

    return render (request, 'respuestas.html', {'pre1': pre1[0],'res1': res1, 'res1_op1': res1_op1, 'res1_op2': res1_op2, 'res1_op3': res1_op3, 'res1_op4': res1_op4, 'res1_op5': res1_op5})

class reporte(View):  
     
    def cabecera(self,pdf):
        #Establecemos el tamaño de letra en 16 y el tipo de letra Helvetica
        pdf.setFont("Helvetica", 16)
        #Dibujamos una cadena en la ubicación X,Y especificada
        pdf.drawString(120, 790, u"Sociedad Guatemalteca de Talento Humano")
        pdf.setFont("Helvetica", 14)
        pdf.drawString(200, 770, u"Encuesta de Salud")
               
         
    def get(self, request, *args, **kwargs):
        #Indicamos el tipo de contenido a devolver, en este caso un pdf
        response = HttpResponse(content_type='application/pdf')
        #La clase io.BytesIO permite tratar un array de bytes como un fichero binario, se utiliza como almacenamiento temporal
        buffer = BytesIO()
        #Canvas nos permite hacer el reporte con coordenadas X y Y
        pdf = canvas.Canvas(buffer, pagesize=A4)
        #Llamo al método cabecera donde están definidos los datos que aparecen en la cabecera del reporte.
        pre1 = list(pregunta1.objects.all())
        res1 = list(opciones1.objects.values('opcion'))
        res1_op1 = res1.count({'opcion': 'Poco Saludable'})
        res1_op2 = res1.count({'opcion': 'Regular Saludable'})
        res1_op3 = res1.count({'opcion': 'Saludable'})
        res1_op4 = res1.count({'opcion': 'Muy Saludable'})
        res1_op5 = res1.count({'opcion': 'Excelente Saludable'})  
        self.cabecera(pdf) 
        pdf.setFont("Helvetica", 12)
        d = Drawing(20, 20)
        bar = VerticalBarChart()
        bar.x = 50
        bar.y = 50
        op1 = ['PS', 'RS', 'S', 'MS', 'ES']
        bar.data = [[res1_op1],[res1_op2], [res1_op3], [res1_op4], [res1_op5]]
        bar.categoryAxis.categoryNames = op1

        bar.width = 200
        bar.height = 200
        bar.valueAxis.rangeRound = 'both'
        bar.valueAxis.valueMax = 10
        bar.valueAxis.forceZero = 1
        bar.bars.fillColor   = PCMYKColor(100,200,100,40,alpha=45)
    
        d.add(bar, '')
        pdf.setFont("Helvetica", 12)
        pdf.drawString(75,700, str(pre1[0]))


        pdf.setTitle("Comparacion de Resultados")
        renderPDF.draw(d, pdf, 150, 400)   
        pdf.showPage()
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

encuesta/templates/opciones/crear.html
{% extends 'index.html' %}

{% block title %}
    Creación Persona
{% endblock title %}

{% block body %}
 <h1>Hola mundo</h1>
    
{% endblock body %}

encuesta/templates/opciones/listar.html
{% extends 'index.html' %} 
{% block title %} Preguntas 
{% endblock title %} 
{%block body %}
<form method="POST">
  {% csrf_token %}
  <div class="card">
    <div class="card-header">
      Preguntas
    </div>
    <div class="card-body">
      <h5 class="card-title"> 1. 
        {% for pregunta in pre1 %}
        {{ pregunta.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr>
          <th><label for="id_opcion">Opcion:</label></th>
          <td>
            <select name="opcion" required id="id_opcion">
              <option value="">---------</option>
              <option value="Poco Saludable">Poco Saludable</option>
              <option value="Regular Saludable">Regular Saludable</option>
              <option value="Saludable">Saludable</option>
              <option value="Muy Saludable" selected>Muy Saludable</option>
              <option value="Excelente Saludable">Excelente Saludable</option>
            </select>
          </td>
        </tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 2. 
        {% for pregunta2 in pre2 %}
        {{ pregunta2.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta2"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr><th><label for="id_opcion2">Opcion:</label></th><td>
        <select name="opcion2" required id="id_opcion2">
          <option value="">---------</option>
          <option value="SI">SI</option>
          <option value="NO" selected>NO</option>
        </select></td></tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 3. 
        {% for pregunta3 in pre3 %}
        {{ pregunta3.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta3"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr><th><label for="id_opcion3">Opcion:</label></th><td>
        <select name="opcion3" required id="id_opcion3">
          <option value="">---------</option>
          <option value="Presión alterial Alta">Presión alterial Alta</option>
          <option value="Diabetes">Diabetes</option>
          <option value="Hemofilia">Hemofilia</option>
          <option value="Otro">Otro</option>
          <option value="Ninguna" selected>Ninguna</option>
        </select></td></tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 4.
        {% for pregunta4 in pre4 %}
        {{ pregunta4.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta4"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr><th><label for="id_opcion4">Opcion:</label></th><td></td>
        <select name="opcion4" required id="id_opcion4">
              <option value="">---------</option>
              <option value="Si, a ambos">Si, a ambos</option>
              <option value="Solo a las Drogas">Solo a las Drogas</option>
              <option value="Solo al alcohol">Solo al alcohol</option>
              <option value="Ninguna" selected>Ninguna</option>
        </select></td></tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 5.
        {% for pregunta5 in pre5 %}
        {{ pregunta5.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta5"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr>
          <th><label for="id_opcion5">Opcion:</label></th>
          <td>
            <select name="opcion5" required id="id_opcion5">
              <option value="">---------</option>
              <option value="Una vez cada 3 meses">Una vez cada 3 meses</option>
              <option value="Una vez cada 6 meses">Una vez cada 6 meses</option>
              <option value="Una vez cada al año">Una vez cada al año</option>
              <option value="Solo cuando es necesario">Solo cuando es necesario</option>
              <option value="Nunca lo hago" selected>Nunca lo hago</option>
            </select>
          </td>
        </tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 6.
        {% for pregunta6 in pre6 %}
        {{ pregunta6.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta6"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr>
          <th><label for="id_opcion6">Opcion:</label></th>
          <td>
            <select name="opcion6" required id="id_opcion6">
              <option value="">---------</option>
              <option value="Excelente">Excelente</option>
              <option value="Muy Bien">Muy Bien</option>
              <option value="Promedio" selected>Promedio</option>
              <option value="Mal">Mal</option>
              <option value="Muy mal">Muy mal</option>
            </select>
          </td>
        </tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 7.
        {% for pregunta7 in pre7 %}
        {{ pregunta7.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta7"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr>
          <th><label for="id_opcion7">Opcion:</label></th>
          <td>
            <select name="opcion7" required id="id_opcion7">
              <option value="">---------</option>
              <option value="Excelente Capacidad">Excelente Capacidad</option>
              <option value="Buena Capacidad">Buena Capacidad</option>
              <option value="Capacidad Moderada" selected>Capacidad Moderada</option>
              <option value="Deterioro Grave Capacidad">Deterioro Grave Capacidad</option>
              <option value="Deterioro total de la Capacidad">Deterioro total de la Capacidad</option>
            </select>
          </td>
        </tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 8.
        {% for pregunta8 in pre8 %}
        {{ pregunta8.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta8"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr>
          <th><label for="id_opcion8">Opcion:</label></th>
          <td>
            <select name="opcion8" required id="id_opcion8">
              <option value="">---------</option>
              <option value="Sin ayuda" selected> Sin ayuda</option>
              <option value="Con algo de ayuda'">Con algo de ayuda'</option>
              <option value="Completamente con ayuda">Completamente con ayuda</option>
            </select>
          </td>
        </tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 9.
        {% for pregunta9 in pre9 %}
        {{ pregunta9.texto }}
        {% endfor %}
      </h5>
      <p class="card-text">
        <input
          type="number"
          name="encuesta9"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr>
          <th><label for="id_opcion9">Opcion:</label></th>
          <td>
            <select name="opcion9" required id="id_opcion9">
              <option value="">---------</option>
              <option value="Completamente desacuerdo">Completamente desacuerdo</option>
              <option value="Algo en desacuerdo">Algo en desacuerdo</option>
              <option value="Neutral" selected>Neutral</option>
              <option value="Un poco acuerdo">Un poco acuerdo</option>
              <option value="Completamente acuerdo">Completamente acuerdo</option>
            </select>
          </td>
        </tr>
      </p>
    </div>
    <div class="card-body">
      <h5 class="card-title"> 10.
        {% for pregunta10 in pre10 %}
        {{ pregunta10.texto }}
        {% endfor %}
      </h5>e
      <p class="card-text">
        <input
          type="number"
          name="encuesta10"
          style="visibility:hidden"
          value="{{ usuario }}"
        />
        <tr><th><label for="id_opcion10">Opcion:</label></th><td>
        <select name="opcion10" required id="id_opcion10">
          <option value="">---------</option>
          <option value="SI">SI</option>
          <option value="NO" selected>NO</option>
        </select></td></tr>
      </p>
    </div>
    <div class="card-body">
        <button type="submit">Enviar</button>
    </div>
  </div>


</form>

{% endblock body %}